### ISSUE TITLE
some gentle feedback

### ISSUE THREAD

**Issue by mavenraven** [RyanCarrier/dijkstra#10]
Hey, I happened to be looking at how other people implemented dijkstra's in golang.  You can't use dijkstra's to solve the longest path problem. See https://en.wikipedia.org/wiki/Longest_path_problem

Hope you find this helpful!

**Comment by RyanCarrier** [comment]
best, err := graph.Longest(0,2) will give longest path assuming all are verticies weight are even.
Can you give example of how it doesn't?
