### ISSUE TITLE
The shortest distance result problem

### ISSUE THREAD

**Issue by baili-tang** [RyanCarrier/dijkstra#15]
How can different shortest distance results exist when the same data, the same starting point and end point are calculated and tested several times

**Comment by RyanCarrier** [comment]
If going north gets you there in 4minutes, going east gets you there in 4 minutes,  but then going south takes 40 minutes, then both north and east are the fastest

Can you give an example of the issue you're experiencing

**Comment by baili-tang** [comment]
I get ,  Because there are decimals like 0.1 in my distance calculation, which are rounded to 0, this problem appears. Multiply the value by 100 times 10 to get the solution. thank you
