### ISSUE TITLE
 Is it concurrency safe?

### ISSUE THREAD

**Issue by baili-tang** [RyanCarrier/dijkstra#16]

**Comment by RyanCarrier** [comment]
Having a look :)

**Comment by RyanCarrier** [comment]
If you mean call shortest while one is still processing, IE; have one graph, and calling shortest on it 3 times before the first has finished, yeah that will fail. it keeps it's state information within the graph itself, this is to not waste time when updating it, or say if an arc updates and you don't want everything to have to fully reprocess

If you mean have two graphs working at the same time, I have no idea why it wouldn't be working concurrently but I'll check incase I'm crazy...

**Comment by RyanCarrier** [comment]
Could pretty easily adjust to make the state held in the shortest method, but yeah then we lose state information for following runs of shortest which I think would be a pretty net negative? 

Am I understanding correctly?

Would it be best to return an error if shortest is already running? Or reset it?

**Comment by RyanCarrier** [comment]
Oof sorry I mean, keeps state information so you can go through and check what's happening, it doesn't do partial updates.

**Comment by RyanCarrier** [comment]
Have set it now that it will return error if you run while it's already calculating. Let me know if I've missinterpreted, also added tests for concurrent testing of different graphs just to make sure that's not what you meant.

**Comment by RyanCarrier** [comment]
Update to v1.2.0 for fix

**Comment by nprintz** [comment]
> it keeps it's state information within the graph itself, this is to not waste time when updating it, or say if an arc updates and you don't want everything to have to fully reprocess

I'm unfamiliar with the innards of the dijkstra repo code, so take my thoughts with a grain of salt, but could we put a sync.RWMutex on the Graph struct so that operations updating state information in the graph require locking first before modifying. Then readers acquire a read lock to allow for multiple concurrent readers that aren't changing state information?

**Comment by RyanCarrier** [comment]
Yeah you could, but if you are at the point and you are doing the requesting and reading in different threads/routines, you would probably be implementing that yourself, so like; calculate, wait for result, pass result to other thread.

I don't think it makes sense to add a lock to the graph itself, more so to your use case of it as I feel like the default and normal way would be to define graph, then get the resulting path. 

Could be as simple as like go ()func{resultChannel<-graph.Shortest()}()


I feel like I'm probably missing something here though, so if you have some source code I can look at and see the problem you're dealing with I might agree with you
