### ISSUE TITLE
crash, any idea?

### ISSUE THREAD

**Issue by ckcfcc** [RyanCarrier/dijkstra#17]
goroutine 3403 [running]:
runtime.throw({0x8d5419?, 0x40?})
        /usr/local/Cellar/go/1.19.3/libexec/src/runtime/panic.go:1047 +0x5d fp=0xc00b099568 sp=0xc00b099538 pc=0x43537d
runtime.sigpanic()
        /usr/local/Cellar/go/1.19.3/libexec/src/runtime/signal_unix.go:842 +0x2c5 fp=0xc00b0995b8 sp=0xc00b099568 pc=0x44ad85
github.com/RyanCarrier/dijkstra.priorityQueueLong.Less(...)
        /Users/dark/dev_lib/go/pkg/mod/github.com/!ryan!carrier/dijkstra@v1.1.0/priority_queue.go:49
github.com/RyanCarrier/dijkstra.(*priorityQueueLong).Less(0x44c3b4?, 0x40?, 0x827d60?)
        <autogenerated>:1 +0x3f fp=0xc00b0995d8 sp=0xc00b0995b8 pc=0x7080ff
github.com/RyanCarrier/dijkstra.(*priorityQueueWrapper).down(0xc00c95aff0, 0x0, 0x9)
        /Users/dark/dev_lib/go/pkg/mod/github.com/!ryan!carrier/dijkstra@v1.1.0/priority_queue.go:128 +0x104 fp=0xc00b099620 sp=0xc00b0995d8 pc=0x707504
github.com/RyanCarrier/dijkstra.(*priorityQueueWrapper).PopOrdered(0xc00c95aff0)
        /Users/dark/dev_lib/go/pkg/mod/github.com/!ryan!carrier/dijkstra@v1.1.0/priority_queue.go:82 +0x5d fp=0xc00b099650 sp=0xc00b099620 pc=0x7072dd
github.com/RyanCarrier/dijkstra.(*Graph).postSetupEvaluate(0xc0000760a0, 0x1?, 0x326, 0x1)
        /Users/dark/dev_lib/go/pkg/mod/github.com/!ryan!carrier/dijkstra@v1.1.0/dijkstra.go:108 +0x87 fp=0xc00b0996f8 sp=0xc00b099650 pc=0x705ac7
github.com/RyanCarrier/dijkstra.(*Graph).evaluate(0x8d4972?, 0xc00c88a39c?, 0x4?, 0x1?)
        /Users/dark/dev_lib/go/pkg/mod/github.com/!ryan!carrier/dijkstra@v1.1.0/dijkstra.go:99 +0x55 fp=0xc00b099748 sp=0xc00b0996f8 pc=0x7059f5
github.com/RyanCarrier/dijkstra.(*Graph).Shortest(...)
        /Users/dark/dev_lib/go/pkg/mod/github.com/!ryan!carrier/dijkstra@v1.1.0/dijkstra.go:9
jyClient/client/resMgr.(*MapGraph).SearchPath(0xc0009c1160, 0x23b4?, 0x23bf)
        /Users/dark/dev_projects/JYOline/jyClient/client/resMgr/mapGraph.go:135 +0x19f fp=0xc00b0997f0 sp=0xc00b099748 pc=0x70bcdf
jyClient/client/resMgr.(*ResMgr).GetMap2MapPath(...)
        /Users/dark/dev_projects/JYOline/jyClient/client/resMgr/mapGraph.go:56
jyClient/client/resMgr.(*ResMgr).FindNearBigMap(0xc000124b40, 0x23b4, {0xca14f8?, 0x0, 0x1?})
        /Users/dark/dev_projects/JYOline/jyClient/client/resMgr/resource.go:141 +0xcc fp=0xc00b099840 sp=0xc00b0997f0 pc=0x71078c
jyClient/client/scriptMgr.(*ScriptManager).cmdInternalWork(0xc009ae5020, {0xc006e39d80, 0x6}, {0x8d7342, 0x9}, {0x0, 0x0})
        /Users/dark/dev_projects/JYOline/jyClient/client/scriptMgr/cmd_work.go:701 +0x1a6a fp=0xc00b0999e0 sp=0xc00b099840 pc=0x7d2b0a
jyClient/client/scriptMgr.(*ScriptManager).CMDWork(0xc009ae5020?, {0xc006e39d80?, 0xc006e39d80?}, {0x8d7342?, 0xc0000e1090?})
        /Users/dark/dev_projects/JYOline/jyClient/client/scriptMgr/cmd_work.go:538 +0xd3 fp=0xc00b099a58 sp=0xc00b0999e0 pc=0x7d0f93

**Comment by ckcfcc** [comment]
func (rs *ResMgr) GetMap2MapPath(src, tgt uint16) (edges []*Edge) {
	_, edges = rs.mg.SearchPath(src, tgt)
	return
}

**Comment by RyanCarrier** [comment]
Can you add your data or send it to me

from quick glance looks like Less is probably getting called on indexes that don't exist... which I'm not sure how that would happen...

will have a proper look over next couple of days
