### ISSUE TITLE
Is this package thread safe?

### ISSUE THREAD

**Issue by kolkov** [RyanCarrier/dijkstra#18]
Can I access it from different goroutines almost simultaneously while the first calculation is still in progress?
My application uses this package to find a shorter path through the railroad lines and acts as a backend for a web service.  If multiple requests arrive almost simultaneously, then those requests will fail.

**Comment by RyanCarrier** [comment]
I think I understand you, want to be able to solve different paths concurrently? I've just updated to 1.3, this has ShortestSafe which will let you run multiple with no issue (assuming no underlying graph changes)

I think that is what you were going for? if not let me know and re-open 770e05828861da4f7cc64b328c6c18286caa2fb4
