### ISSUE TITLE
Find paths in goroutines

### ISSUE THREAD

**Issue by LdDl** [RyanCarrier/dijkstra#3]
Hello,
My programm panics (occasionally) with "invalid memory address..." when I try to call method "Shortest" for Graph struct in multiple goroutines.

> panic: runtime error: invalid memory address or nil pointer dereference
> [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x48e1a7]
> 
> goroutine 12 [running]:
> github.com/RyanCarrier/dijkstra.(*Graph).postSetupEvaluate(0xc4200ae140, 0x0, 0x2, 0xffffffffffffff01, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
>         /home/keep/work/src/github.com/RyanCarrier/dijkstra/dijkstra.go:114 +0x87
> github.com/RyanCarrier/dijkstra.(*Graph).evaluate(0xc4200ae140, 0x0, 0x2, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
>         /home/keep/work/src/github.com/RyanCarrier/dijkstra/dijkstra.go:104 +0x76
> github.com/RyanCarrier/dijkstra.(*Graph).Shortest(0xc4200ae140, 0x0, 0x2, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
>         /home/keep/work/src/github.com/RyanCarrier/dijkstra/dijkstra.go:7 +0x48
> main.Do(0xc4200ae140)
>         /home/keep/main.go:34 +0x3d
> created by main.main
>         /home/keep/main.go:29 +0x258

Is this supposed to happen? Maybe I do something wrong... If I do, what exactly?
My source code:

```
package main
import (
	"fmt"
	"log"

	"github.com/RyanCarrier/dijkstra"
)

func main() {
	graph := dijkstra.NewGraph()
	//Add the 3 verticies
	graph.AddVertex(0)
	graph.AddVertex(1)
	graph.AddVertex(2)
	//Add the arcs
	graph.AddArc(0, 1, 1)
	graph.AddArc(0, 2, 1)
	graph.AddArc(1, 0, 1)
	graph.AddArc(1, 2, 2)
	best, err := graph.Shortest(0, 2)
	if err != nil {
		log.Fatal(err)
	}
	fmt.Println(best)
	for i := 0; i < 1000; i++ {
		go Do(graph)
	}
}

func Do(graph *dijkstra.Graph) {
	_, err := graph.Shortest(0, 2)
	if err != nil {
		log.Fatal(err)
	}
}
```

**Comment by RyanCarrier** [comment]
It's state dependant. So the state of the dijkstra struct changes as it's calculating the shortest path. If another thread starts calculating from the start, while the original thread isn't done. They will conflict as they try to apply their own changes over one another.

There should be no circumstance when you should need to check for the shortest path, while the shortest path is already being calculated by the same graph.

The code is working as intended.

**Comment by LdDl** [comment]
so:
To find, for example, two shortest pathes A -> B, X -> Y, I should do something like this:
without goroutines, just line by line:

> ...stuff
> graph.Shortest(1, 20)
> graph.Shortest(1050, 109)
> ...stuff

or I should have 2 instances of same graph (which are the same):
> graphOne := dijkstra.NewGraph()
> graphTwo := dijkstra.NewGraph()
> ....fill graphs with same data
> go graphOne.Shortest(1, 20)
> go graphTwo.Shortest(1050, 109)
> ...stuff

right?

**Comment by RyanCarrier** [comment]
Ahhhh, I see, yeah you would need a second one.
Or as you said line by line, in sequence.
