### ISSUE TITLE
about load balance

### ISSUE THREAD

**Issue by hepeng235767** [RyanCarrier/dijkstra#5]
Hi ryan:
  beautiful code ! hard work ! isn't it ?  if any idea about considering load balance in dijkstra algorithm? just like implemented in network router !

**Comment by RyanCarrier** [comment]
What do you mean sorry? As in using it for load balancing? You would just set the weights of each arc to the latency between servers.

**Comment by hepeng235767** [comment]
for example , from server a to server b , we could spread to different path  from a , but finally reach b at the same cost . also it occurs recursively during the middle path . this is the realistic situation like navigationn , routing protocols and so on .

**Comment by RyanCarrier** [comment]
Ahh, so if there is more than 1 path of same weight, show them all as results?

**Comment by hepeng235767** [comment]
Yeah，Thus , bestVertex could be a slice , but i find in linked-list.go 129-131 that it may misordered the priority queue .

**Comment by RyanCarrier** [comment]
Yeah I see no problem with that. I'll try get on it this weekend, shoudl be a small update

**Comment by tegk** [comment]
Was this implemented?

**Comment by hepeng235767** [comment]
yeah , implemented last year .  how i show the code

**Comment by tegk** [comment]
How to I get multiple shortest paths then with this code?

`best, err := graph.Shortest(0,11)
	if err!=nil{
		log.Fatal(err)
	}

	fmt.Println("Shortest distance ", best.Distance, " following path ", best.Path)`

**Comment by RyanCarrier** [comment]
Sorry for delay
